### ISSUE TITLE
Updates to map

### ISSUE THREAD

**Issue by JonasKaad** [JonasKaad/BachelorProject#23]
- Add some kind of direction, to show which way the flight is going
- Add option to clear map. (Either on next flight load or button)
- Possibility to click on next flight (list of them)
-- click on 10-15 flights to quickly load in

**Comment by VictorABoye** [comment]
We could also add a "save" button, so that when you find a route that has a holding pattern it is easy to save to a json file

**Comment by JonasKaad** [comment]
Add padding for flight data going around the world (+180/-180) for the visualizer
![image](https://user-images.githubusercontent.com/36827320/226893828-40f1a2a1-a75d-4efd-a70c-eb7969e4ec01.png)
